name: Refresh Todays Deals

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: Production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REVALIDATION_SECRET: ${{ secrets.REVALIDATION_SECRET }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: pnpm install

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run Deals Scrape
        run: pnpm run scrape-deals
